name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test
